name: Clean up registry

on:
  pull_request:
    branches: [main]
    types: [closed, opened, synchronize]

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Ghcr.io Cleanup Action
        uses: dataaxiom/ghcr-cleanup-action@v1.0.13
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ github.event.action != 'closed' }}
          delete-untagged: true
          delete-orphaned-images: true
          delete-tags: ${{ github.head_ref }}